services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    environment:
      - TZ=UTC
      - N8N_HOST=n8n.devroad.online
    volumes:
      - n8n-data:/home/node/.n8n
    networks:
      - primary
    restart: unless-stopped

networks:
  primary:
    external: true

volumes:
  n8n-data:
